# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'r:\ESLocalizeTool\UIDlgAlert.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MsgBox(object):
    def setupUi(self, MsgBox):
        MsgBox.setObjectName("MsgBox")
        MsgBox.resize(320, 160)
        MsgBox.setMinimumSize(QtCore.QSize(320, 160))
        MsgBox.setMaximumSize(QtCore.QSize(320, 160))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/png/resources/es_icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon.addPixmap(QtGui.QPixmap(":/png/resources/es_icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        MsgBox.setWindowIcon(icon)
        self.btnClose = QtWidgets.QPushButton(MsgBox)
        self.btnClose.setGeometry(QtCore.QRect(100, 120, 116, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(13)
        font.setBold(False)
        font.setWeight(50)
        self.btnClose.setFont(font)
        self.btnClose.setStyleSheet("background-color: rgb(32, 74, 135);\n"
"color: rgb(243, 243, 243);")
        self.btnClose.setObjectName("btnClose")
        self.lb_Msg = QtWidgets.QLabel(MsgBox)
        self.lb_Msg.setGeometry(QtCore.QRect(145, 15, 81, 24))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(18)
        self.lb_Msg.setFont(font)
        self.lb_Msg.setText("")
        self.lb_Msg.setTextFormat(QtCore.Qt.PlainText)
        self.lb_Msg.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lb_Msg.setObjectName("lb_Msg")
        self.lb_err = QtWidgets.QLabel(MsgBox)
        self.lb_err.setGeometry(QtCore.QRect(15, 50, 291, 51))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.lb_err.setFont(font)
        self.lb_err.setStyleSheet("color: rgb(204, 0, 0);")
        self.lb_err.setLineWidth(2)
        self.lb_err.setText("")
        self.lb_err.setAlignment(QtCore.Qt.AlignCenter)
        self.lb_err.setWordWrap(True)
        self.lb_err.setObjectName("lb_err")
        self.lb_icon = QtWidgets.QLabel(MsgBox)
        self.lb_icon.setGeometry(QtCore.QRect(110, 15, 24, 24))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(13)
        self.lb_icon.setFont(font)
        self.lb_icon.setStyleSheet("")
        self.lb_icon.setText("")
        self.lb_icon.setObjectName("lb_icon")

        self.retranslateUi(MsgBox)
        QtCore.QMetaObject.connectSlotsByName(MsgBox)

    def retranslateUi(self, MsgBox):
        _translate = QtCore.QCoreApplication.translate
        MsgBox.setWindowTitle(_translate("MsgBox", "Message"))
        self.btnClose.setText(_translate("MsgBox", "OK"))
import resource_rc
